'use client'
import './globals.scss'
import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import {useState} from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [str, setStr] = useState();
  const searchWord = (x)=>{
    x?setStr(x):null;
  }
  return (
    <html lang="en">
    <body className={inter.className}>
        <Header
            searchWord={searchWord}
        />
        {children}
      </body>
    </html>
  )
}
